export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_RESET_TOKEN: (token: string) => `/auth/verify-reset-token/${token}`,
    CHANGE_PASSWORD: "/auth/change-password",
    GOOGLE: "/auth/google",
    GOOGLE_CALLBACK: "/auth/google/callback",
  },
  COMPANY: {
    CREATE: "/companies",
    GetAll: "/companies",
    GetOne: (id: string | number) => `/companies/${id}`,
    UPDATE: (id: string | number) => `/companies/${id}`,
    DELETE: (id: string | number) => `/companies/${id}`,
  },
  CONTACT: {
    CREATE: "/contacts",
    GetAll: "/contacts",
    GetOne: (id: string | number) => `/contacts/${id}`,
    UPDATE: (id: string | number) => `/contacts/${id}`,
    DELETE: (id: string | number) => `/contacts/${id}`,
  },
  EMPLOYEE: {
    CREATE: "/employees",
    GetAll: "/employees",
    GetOne: (id: string | number) => `/employees/${id}`,
    UPDATE: (id: string | number) => `/employees/${id}`,
    DELETE: (id: string | number) => `/employees/${id}`,
    INVITE: "/employees/invite",
  },
  DEAL: {
    CREATE: "/deals",
    GetAll: "/deals",
    GetOne: (id: string | number) => `/deals/${id}`,
    UPDATE: (id: string | number) => `/deals/${id}`,
    DELETE: (id: string | number) => `/deals/${id}`,
  },
  ORDER: {
    CREATE: "/orders",
    GetAll: "/orders",
    GetOne: (id: string | number) => `/orders/${id}`,
    UPDATE: (id: string | number) => `/orders/${id}`,
    DELETE: (id: string | number) => `/orders/${id}`,
  },
  ROLE: {
    CREATE: "/roles",
    GetAll: "/roles",
    GetOne: (id: string | number) => `/roles/${id}`,
    UPDATE: (id: string | number) => `/roles/${id}`,
    DELETE: (id: string | number) => `/roles/${id}`,
  },
  TICKET: {
    CREATE: "/tickets",
    GetAll: "/tickets",
    GetOne: (id: string | number) => `/tickets/${id}`,
    UPDATE: (id: string | number) => `/tickets/${id}`,
    DELETE: (id: string | number) => `/tickets/${id}`,
  },
  PROFILE: {
    GET: (id: string | number) => `/profile/${id}`,
    UPDATE: (id: string | number) => `/profile/${id}`,
    CHANGE_PASSWORD: (id: string | number) => `/profile/${id}/password`,
  },
  ANALYTICS: {
    CARDS: "/analytics/cards",
    REVENUE: "/analytics/revenue",
    TICKETS: "/analytics/tickets",
    PRODUCTS: "/analytics/products",
    LEADS: "/analytics/leads",
    DASHBOARD: "/dashboard",
  },
  MISC: {
    HEALTH: "/health",
  },
};
